name: flutter_campus_connected
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  image_test_utils: ^1.0.0
  firebase_auth:
  cloud_firestore:
  image_picker:
  firebase_storage:
  transparent_image:
  connectivity:
  #  google_maps_flutter:
  #  location:
  datetime_picker_formfield:

  cupertino_icons: ^0.1.2
  # firebase_database: ^1.0.5
  font_awesome_flutter: "^8.0.1"


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
  - assets/flutter-icon.png
  - assets/gallery.png
  - assets/person.jpg
  - assets/loadingfailed.png


flutter_icons:
#android: "launcher_icon"
#ios: true
#image_path: "icon/icon.png"